[versions]
paper-api = "26.2.build.+"
minecraft = "26.2"

shadow = "9.6.1"
run-task = "3.1.0"
paperweight-userdev = "2.0.0-beta.23"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight-userdev"}
